### ISSUE TITLE
setVersion(int)' on a null object reference

### ISSUE THREAD

**Issue by GauravCreed** [jgilfelt/android-sqlite-asset-helper#121]
Hi @cyrilmottier 

**Crash Report**
`Fatal Exception: java.lang.RuntimeException: Unable to pause activity {kjvstudybible.bible.kjv.bibleverses.bibleoffline/com.kjv.kjvstudybible.IsiActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.database.sqlite.SQLiteDatabase.setVersion(int)' on a null object reference
       at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:3771)
       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3737)
       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3711)
       at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3685)
       at android.app.ActivityThread.-wrap16(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1502)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:179)
       at android.app.ActivityThread.main(ActivityThread.java:6152)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)`

is there any solutuion for that issue...

Thanks.

**Comment by jon-adams** [comment]
You'll need to provide your code for us to help. But basically, you are trying to access an instance that is null. Read up on Android lifecycles and where and when you're setting various properties, when and where you're storing them, etc.

But my guess, without seeing the code, is that this problem is outside the scope of this library. You should be able to receive help from the general Android community on how to work with Android lifecycles properly.

**Comment by GauravCreed** [comment]
Okay let me check and inform you.
