### ISSUE TITLE
NullPointerException in getWritableDatabase()

### ISSUE THREAD

**Issue by CoolMind** [jgilfelt/android-sqlite-asset-helper#63]
Hello!
In 
```java
public synchronized SQLiteDatabase getWritableDatabase() 
```
at a line 
```java
int version = db.getVersion();
```
a NullPointerException appeared on LG D686.

**Comment by Jorgesys** [comment]
your database instantiation is null, your database must be inside the  /assets/databases/ folder.

**Comment by CoolMind** [comment]
@Jorgesys, thank you for your mention. We develop an application listed in Play Market. So, on many devices it works alright, but in some cases we receive crashlogs with this error. We hold a database in a folder /assets. Because I rewrote some methods for our needs, I suspect a problem may occur in procedure copyDatabaseFromAssets which I rewrote.

**Comment by Maheshws** [comment]
I have same issue with only Moto G users. It works perfect for all other devices.

**Comment by CoolMind** [comment]
@Maheshws, glad to hear it. Yes, it's a difficult to repeat sitiation. If I succeed in resolving the problem, I will speak about a solution here.

**Comment by RobGThai** [comment]
Are you by any chances initialising the database from multiple places? I had the same problem and spent today tracing the root cause of this problem. Our problem was that we also sync the database zip file replacing bundled zip file.

So we start checking & downloading our file on the MainActivity. We also open the database to set up some master data inside Application. With that we get two random crashes.

1. When the file is downloading and we try to unpack the database, we get one error.
2. In the instance where we don't need to download the file, we continue to unpack database right away. If this happen while the first unpacking has not finished, we get another error.

For example:

    W/SQLiteAssetHelper﹕ copying database from assets...
    extracting file: 'category.sqlite'...
    Failed to open database '/data/data/<app_id>/databases/category'.
    android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
            at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
            at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:209)
            at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
            at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
            at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
            at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
            at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:806)
            at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:794)
            at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
            at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:669)
            at com.readystatesoftware.sqliteasset.SQLiteAssetHelper.returnDatabase(SQLiteAssetHelper.java:408)
            at com.readystatesoftware.sqliteasset.SQLiteAssetHelper.createOrOpenDatabase(SQLiteAssetHelper.java:386)
            at com.readystatesoftware.sqliteasset.SQLiteAssetHelper.getWritableDatabase(SQLiteAssetHelper.java:176)
            at com.readystatesoftware.sqliteasset.SQLiteAssetHelper.getReadableDatabase(SQLiteAssetHelper.java:254)
    W/SQLiteAssetHelper﹕ could not open database category - unknown error (code 14): Could not open database
    W/SQLiteAssetHelper﹕ copying database from assets...
    W/SQLiteAssetHelper﹕ extracting file: 'category.sqlite'...
    W/SQLiteAssetHelper﹕ database copy complete
    I/SQLiteAssetHelper﹕ successfully opened database category

Comparing this to the success log:

    W/SQLiteAssetHelper﹕ copying database from assets...
    W/SQLiteAssetHelper﹕ extracting file: 'category.sqlite'...
    W/SQLiteAssetHelper﹕ database copy complete
    I/SQLiteAssetHelper﹕ successfully opened database category

Not sure if it helps.

**Comment by SyedWasiHaider** [comment]
This is a pretty serious bug. On our app, it only occurs if you do a clean install on a clean phone (like completely reset).

**Comment by CoolMind** [comment]
Thanks for your answers. I noticed a problem had also occured before: https://github.com/jgilfelt/android-sqlite-asset-helper/issues/36

**Comment by 1stLyte** [comment]
I am experiencing a similar problem on Xperia X2 (4.4.4) - here is a sample of the log (works fine on other devices)

12-05 15:56:12.365 W/SQLiteAssetHelper(12204): copying database from assets...
31	12-05 15:56:12.385 W/SQLiteAssetHelper(12204): database copy complete
32	12-05 15:56:12.385 E/SQLiteLog(12204): (1) near \"WITHOUT\": syntax error
33	12-05 15:56:12.385 E/SQLiteLog(12204): (11) database corruption at line 93710 of [00bb9c9ce4]
34	12-05 15:56:12.385 E/SQLiteLog(12204): (11) malformed database schema (Keys) - near \"WITHOUT\": syntax error
35	12-05 15:56:12.385 E/DefaultDatabaseErrorHandler(12204): Corruption reported by sqlite on database: /data/data/database.db
36	12-05 15:56:12.385 E/DefaultDatabaseErrorHandler(12204): deleting the database file: /data/data/database.db
37	12-05 15:56:12.385 E/SQLiteLog(12204): (14) cannot open file at line 30191 of [00bb9c9ce4]
38	12-05 15:56:12.385 E/SQLiteLog(12204): (14) os_unix.c:30191: (2) open(/data/data/database.db) -
39	12-05 15:56:12.395 E/SQLiteDatabase(12204): Failed to open database '/data/data/database.db'.
40	12-05 15:56:12.395 E/SQLiteDatabase(12204): android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database

Notes:
1 Full database name changed to database.db in above log snippet
2. database in assets is not zipped and is quite small
3. This leads to NPE as follows :
java.lang.NullPointerException
com.readystatesoftware.sqliteasset.SQLiteAssetHelper.getWritableDatabase(SQLiteAssetHelper.java:178)
com.readystatesoftware.sqliteasset.SQLiteAssetHelper.getReadableDatabase(SQLiteAssetHelper.java:254)

4 It would be nice to have this sort of failure trapped and passed back so that can be handled better

**Comment by CoolMind** [comment]
@1stLyte, thanks!
I thinks this library is not supported anymore.
So, probably we should find another one. I found it at StackOverflow.com after a recommendation of CommonsWare.

**Comment by jon-adams** [comment]
@CoolMind This library is still supported as much as any open source Android library that is run by one or two people is. And as far as I know, it still works on the majority of devices. We use it for our production apps and haven't had any issues with it. So, I guess I'm saying don't discourage users from reporting issues on certain devices.

**Comment by mnjrupp** [comment]
I use it for my dictionary app and have had no issues as on now
https://play.google.com/store/apps/details?id=com.rupp.android.dic.webster

**Comment by jon-adams** [comment]
I didn't mean to imply it should work for everyone. I'm sure there are bugs or quirks with certain devices. The Android ecosystem is a messy one.

**Comment by Ansh1234** [comment]
Facing a very similar issue . Getting null at the following line. Problem only on select devices. Not able to reproduce.

`db.getVersion()`

Is there any solution for this problem ?

**Comment by Kisty** [comment]
@Ansh1234 It could be a database lock issue? Is it the first time you're interacting with the database? Is it on start up or at another time? What devices does it happen on?

**Comment by PurTahan** [comment]
HI
I had this problem. after many searches and many tests, i find how to fix this.
when database contains table(s) without rowid!!! , database file will deleted.
make sure your tables have rowid....

**Comment by CoolMind** [comment]
@PurTahan, thank you for your solution! I hope it will help other developers.

**Comment by Kisty** [comment]
@PurTahan @CoolMind is that a column with the name '_id' as in [BaseColumns._ID](https://developer.android.com/reference/android/provider/BaseColumns.html#_ID)?

**Comment by mukhamedissa** [comment]
Hello everybody. What about this problem? Has anybody found a solution?

**Comment by aulawebonline** [comment]
Has anybody found a solution?

**Comment by jarig** [comment]
Having the same kind of issue, also on set of devices...

**Comment by mukhamedissa** [comment]
So, anyone who still have this problem, is your dbmanager initialized in Application class?
