### ISSUE TITLE
no such table error when trying to open db using sqlite-asset-helper

### ISSUE THREAD

**Issue by sunladyjoy** [jgilfelt/android-sqlite-asset-helper#93]
I've added the gradle dependency for SQLiteAssetHelper and I [researched](http://stackoverflow.com/questions/32939748/sqliteassethelper-no-such-table-error) and re-copied my database into the databases folder (within the assets folder) yet I'm still getting this error:

[sqliteassethelpererror.pdf](https://github.com/jgilfelt/android-sqlite-asset-helper/files/184514/sqliteassethelpererror.pdf)

[DisplayResult.zip](https://github.com/jgilfelt/android-sqlite-asset-helper/files/184516/DisplayResult.zip)
[MainActivity.zip](https://github.com/jgilfelt/android-sqlite-asset-helper/files/184517/MainActivity.zip)
[MySQLiteHelper.zip](https://github.com/jgilfelt/android-sqlite-asset-helper/files/184518/MySQLiteHelper.zip)
[PromiseListAdapter.zip](https://github.com/jgilfelt/android-sqlite-asset-helper/files/184519/PromiseListAdapter.zip)
[Promises.zip](https://github.com/jgilfelt/android-sqlite-asset-helper/files/184529/Promises.zip)
[verses.zip](https://github.com/jgilfelt/android-sqlite-asset-helper/files/184532/verses.zip)
[activity_main.zip](https://github.com/jgilfelt/android-sqlite-asset-helper/files/184534/activity_main.zip)
[lv_items.zip](https://github.com/jgilfelt/android-sqlite-asset-helper/files/184533/lv_items.zip)
[categories.zip](https://github.com/jgilfelt/android-sqlite-asset-helper/files/184535/categories.zip)

I'm still relatively new to Android Studio.  

Thank you.

**Comment by jon-adams** [comment]
I don't know about others here, but I'm not real keen on opening random PDF documents from the internet. Think you could post the error and stack trace, with the relavant code and file structure, in plain text here? That would help us help you better.

**Comment by Kisty** [comment]
@sunladyjoy Looks fine to me. Can you post your asset folder and can you tell us the path of it by right clicking on the folder and selecting _Copy path_. Maybe the database is in the wrong place. How do you make your database? Is it a SQLite database? Nice idea, btw! :)

This is the stack trace from the PDF:

`03-22 12:23:44.130 3791-3791/? E/SQLiteAssetHelper: Couldn't open cybdatabase.db for writing (will try read-only):
com.readystatesoftware.sqliteasset.SQLiteAssetHelper$SQLiteAssetException: Missing databases/cybdatabase.db file (or .zip, .gz archive) in assets, or target folder not writable
at android.content.res.AssetManager.openAsset(Native Method)
at android.content.res.AssetManager.open(AssetManager.java:313)
at android.content.res.AssetManager.open(AssetManager.java:287)
at com.readystatesoftware.sqliteasset.SQLiteAssetHelper.copyDatabaseFromAssets(SQLiteAssetHelper.java:436)
at com.readystatesoftware.sqliteasset.SQLiteAssetHelper.createOrOpenDatabase(SQLiteAssetHelper.java:400)
at com.readystatesoftware.sqliteasset.SQLiteAssetHelper.getWritableDatabase(SQLiteAssetHelper.java:176)
at com.readystatesoftware.sqliteasset.SQLiteAssetHelper.getReadableDatabase(SQLiteAssetHelper.java:254)
at com.blogspot.joyouslybeingjoy.cybpromises.MySQLiteHelper.getPromiseVerses(MySQLiteHelper.java:23)
at com.blogspot.joyouslybeingjoy.cybpromises.DisplayResult.onCreate(DisplayResult.java:31)
at android.app.Activity.performCreate(Activity.java:6237)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
at android.app.ActivityThread.-wrap11(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
03-22 12:23:44.130 3791-3791/? E/SQLiteLog: (14) cannot open file at line 31278 of [2ef4f3a5b1]
03-22 12:23:44.133 3791-3791/? E/SQLiteLog: (14) os_unix.c:31278: (2) open(/data/user/0/com.blogspot.joyouslybeingjoy.cybpromises/databases/cybdatabase.db) -
03-22 12:23:44.134 3791-3791/? E/SQLiteDatabase: Failed to open database '/data/user/0/com.blogspot.joyouslybeingjoy.cybpromises/databases/cybdatabase.db'.
android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:207)
at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:191)
at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:806)
at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:791)
at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:669)
at com.readystatesoftware.sqliteasset.SQLiteAssetHelper.getReadableDatabase(SQLiteAssetHelper.java:264)
at com.blogspot.joyouslybeingjoy.cybpromises.MySQLiteHelper.getPromiseVerses(MySQLiteHelper.java:23)
at
com.blogspot.joyouslybeingjoy.cybpromises.DisplayResult.onCreate(DisplayResult.java:31)
at android.app.Activity.performCreate(Activity.java:6237)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
at android.app.ActivityThread.-wrap11(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
03-22 12:23:44.135 3791-3791/? D/AndroidRuntime: Shutting down VM
03-22 12:23:44.135 3791-3791/? E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.blogspot.joyouslybeingjoy.cybpromises, PID: 3791
java.lang.RuntimeException: Unable to start activity
ComponentInfo{com.blogspot.joyouslybeingjoy.cybpromises/com.blogspot.joyouslybeingjoy.cybpromises.DisplayResult}
: android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
at android.app.ActivityThread.-wrap11(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error
(code 14): Could not open database
at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:207)
at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:191)
at
android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:806)
at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:791)
at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:669)
at
com.readystatesoftware.sqliteasset.SQLiteAssetHelper.getReadableDatabase(SQLiteAssetHelper.java:264)
at
com.blogspot.joyouslybeingjoy.cybpromises.MySQLiteHelper.getPromiseVerses(MySQLiteHelper.java:23)
at
com.blogspot.joyouslybeingjoy.cybpromises.DisplayResult.onCreate(DisplayResult.java:31)
at android.app.Activity.performCreate(Activity.java:6237)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
at android.app.ActivityThread.-wrap11(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
03-22 12:23:44.169 1630-3602/? W/ActivityManager: Force finishing activity com.blogspot.joyouslybeingjoy.cybpromises/.DisplayResult
03-22 12:23:44.191 1630-3602/? W/ActivityManager: Force finishing activity com.blogspot.joyouslybeingjoy.cybpromises/.MainActivity`

**Comment by sunladyjoy** [comment]
Thanks and I'll post it tomorrow.  Don't have my laptop with me.

:-)

**Comment by sunladyjoy** [comment]
Here's the copy path statement:

C:\Users\Joy\Documents\droid
studio\CYBPromises\app\src\main\assets\databases\cybpromises.db

**Comment by jon-adams** [comment]
The error message says it is looking for `cybdatabase.db` but you apparently named the file `cybpromises.db`. Either change the string you pass to the code to lookup, or rename the file to match.

**Comment by sunladyjoy** [comment]
omg.  I totally missed that!  Thank you!

**Comment by Kisty** [comment]
Cool! Let us know if that fixed it.

**Comment by sunladyjoy** [comment]
Well, I think it did fix the copy database and open database part, now I'm
getting a completely different error:

Process: com.blogspot.joyouslybeingjoy.cybpromises, PID: 2847

java.lang.RuntimeException: Unable to start activity
ComponentInfo{com.blogspot.joyouslybeingjoy.cybpromises/com.blogspot.joyouslybeingjoy.cybpromises.DisplayResult}:
java.lang.NullPointerException: Attempt to invoke interface method 'int
java.util.List.size()' on a null object reference
                                                     at
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                     at
android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                     at
android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                     at
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                     at
android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at
android.os.Looper.loop(Looper.java:148)
                                                     at
android.app.ActivityThread.main(ActivityThread.java:5417)
                                                     at
java.lang.reflect.Method.invoke(Native Method)
                                                     at
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                     at
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                  Caused by:
java.lang.NullPointerException: Attempt to invoke interface method 'int
java.util.List.size()' on a null object reference
                                                     at
com.blogspot.joyouslybeingjoy.cybpromises.PromiseListAdapter.getCount(PromiseListAdapter.java:28)
                                                     at
android.widget.ListView.setAdapter(ListView.java:491)
                                                     at
com.blogspot.joyouslybeingjoy.cybpromises.DisplayResult.onCreate(DisplayResult.java:34)
                                                     at
android.app.Activity.performCreate(Activity.java:6237)
                                                     at
android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                     at
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                     at
android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                     at
android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                     at
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                     at
android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at
android.os.Looper.loop(Looper.java:148)
                                                     at
android.app.ActivityThread.main(ActivityThread.java:5417)
                                                     at
java.lang.reflect.Method.invoke(Native Method)
                                                     at
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)

                                                     at
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

The DisplayResult line is:  dbOpen = new MySQLiteHelper(this);

and the PromiseListAdapter line is:  return promisesList.size();


I'm not quite sure what's going on as that's the first time I saw the
dbOpen line error out.

My query set up looks like:

public Cursor getPromiseVerses() {
    SQLiteDatabase db = getReadableDatabase();
    SQLiteQueryBuilder qb = new SQLiteQueryBuilder();
    String[] sqlSelect = {"category", "book", "chapter", "verse", "word"};
    qb.setTables(TABLE_NAME);

    Cursor c = qb.query(db, sqlSelect,
"category='"+DisplayResult.selectedCategory+"'", null, null, null,
null);
    c.moveToFirst();
    return c;
}

Any insight?

Thanks!

**Comment by jon-adams** [comment]
The relevant part of that stack trace is in your adapter code:

`java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference at com.blogspot.joyouslybeingjoy.cybpromises.PromiseListAdapter.getCount(PromiseListAdapter.java:28)`

which is a purely Java problem. You're calling a method on a null reference. This has nothing to do with this library. You might want to ask for help at Stackoverlow or another general Java coding site.
