### ISSUE TITLE
How do I "install" this helper?

### ISSUE THREAD

**Issue by SirKnowS** [jgilfelt/android-sqlite-asset-helper#94]
Hello,
I've downloaded the android-sqlite-asset-helper zip file but don't know how to install it. Should I extract it to a certain folder? Should I run the batch file?

Sorry if this is an obvious question but I'm new to Android development.

**Comment by jon-adams** [comment]
Follow the [Setup instructions in the documentation](https://github.com/jgilfelt/android-sqlite-asset-helper).

**Comment by SirKnowS** [comment]
Thanks but the setup instructions seem to be for how to use the helper in a project. I need to know where to put the files I extracted from the zip file.

**Comment by jon-adams** [comment]
From what ZIP file? One of the releases? The setup instructions make it so you don't need that to start with.

Or did you download the source for this library to do something with it yourself? If so, what are you trying to do with it that you don't know where to start?

**Comment by SirKnowS** [comment]
On [this page](https://github.com/jgilfelt/android-sqlite-asset-helper), I clicked the "Download ZIP" button and downloaded "android-sqlite-asset-helper-master.zip". I'm assuming I need to put that in my Android Studio/SDK directory so I can then use it in my projects.

Thanks for helping. I just don't know what to do.

**Comment by jon-adams** [comment]
If you're using Android Studio, that means you're using gradle so the better installation method is to use the "dependencies" configuration instead of downloading the JAR manually. Again, the directions on how to do that are on that same page, the Gradle section.

**Comment by atlascoder** [comment]
@SirKnowS just put the following into your build.gradle file for your module (usually app/build.gradle)
and start Sync or just build your project and Gradle will download library in background

**Comment by SirKnowS** [comment]
OK thank you. I get it now.

**Comment by Priyabrata121** [comment]
Hello, I added the dependency in build.gradle and when I sync project, it is telling that "Gradle project sync failed". Please help. Attached the error screenshot. Error(15, 0).

![error](https://user-images.githubusercontent.com/29885287/27820255-76924a66-60bb-11e7-9db6-9bb968a16e9f.PNG)

**Comment by Kisty** [comment]
@Priyabrata121 What version of Android Studio are you running? 2.3.2? 

Try clicking on the _Upgrade plugin to version 2.3.2..._

**Comment by Priyabrata121** [comment]
@Kisty I had version 2.3.2 and the upgrade plugin option was not working. So, I applied the new patch for 2.3.3. Still I get same error message. In the idea.log , I am getting below exception. Please help.

> Caused by: org.gradle.internal.metaobject.AbstractDynamicObject$CustomMessageMissingMethodException: Could not find method compile() for arguments [com.readystatesoftware.sqliteasset:sqliteassethelper:+] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
	at org.gradle.internal.metaobject.AbstractDynamicObject.methodMissingException(AbstractDynamicObject.java:182)
	at org.gradle.internal.metaobject.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:89)
	at build_3mrpgo89fbesxwy2p3wbavns$_run_closure1$_closure4.doCall(C:\Users\mohapriy\AndroidStudioProjects\KidLearningZone\build.gradle:15)
	at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:70)
	at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:160)
	at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:106)

![2](https://user-images.githubusercontent.com/29885287/27836412-fdfc542e-60fc-11e7-935b-9673774451a0.PNG)

**Comment by Kisty** [comment]
Can you post your `build.gradle` and `app/build.gradle` file?

**Comment by Priyabrata121** [comment]
app/build.gradle
`apply plugin: 'com.android.application'

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.3"
    defaultConfig {
        applicationId "com.priya.kidlearningzone"
        minSdkVersion 22
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    productFlavors {
    }
    sourceSets {
        main { assets.srcDirs = ['src/main/assets', 'src/main/assets/', 'src/main/assets/fonts'] }
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.3.1'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    testCompile 'junit:junit:4.12'
}
`
build.gradle:
`buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.3'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }

    dependencies {
        compile 'com.readystatesoftware.sqliteasset:sqliteassethelper:+'
    }

}

allprojects {
    repositories {
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
`

**Comment by Kisty** [comment]
I see the problem. The compile statement should be in your `app/build.gradle` file not the `build.gradle`.

**Comment by Priyabrata121** [comment]
Thank you @Kisty for pointing out my mistake. Now, it is working.

**Comment by Kisty** [comment]
No problem! 

In future, can you post your question on a developer forum like stackoverflow for these kind of problems as the Github issue tracker is more for issues surrounding the library,not for general development. Even better, just Google your error or problem and it will probably come up.
